GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcyNzAzMTQ1NywiZXhwIjoxNzI3MDMxNDcyfQ.EQvHozHyWTt6gUENt3U_e1F5eKNkhzsA5Xw5zEC6v2Y
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcyNzAzMTY1MH0.MI4N2bquvjzIl-GDzCQBYT8lhFJ4x7kgKoxtC2TQcaw"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcyNzAzMTY1MH0.MI4N2bquvjzIl-GDzCQBYT8lhFJ4x7kgKoxtC2TQcaw"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Paul"
}